module.exports = {
  INSECURE_URL_PATTERN: ["localhost", "http://", "127.0.0.1"],
  FAIL: "red",
  SUCCESS: "green",
  INFO: "blue",
  WARN: "yellow",
  MULTIFACTOR_POLICY: {
    empty: "Never",
    "all-applications": "Always",
    "confidence-score": "Use Adaptive MFA",
  },
  MINIMUM_NODE_VERSION: 18,
  DEFAULT_IDLE_SESSION_LIFETIME: "72h",
  DEFAULT_SESSION_LIFETIME: "168h",
  DEFAULT_SESSION_COOKIE_MODE: "persistent",
  CUSTOM_DOMAIN_SCOPE: "read:custom_domains",
  CLIENTS_SCOPE: "read:clients",
  DBCONNECTIONS_SCOPE: "read:connections",
  ATTACK_PROTECTION_SCOPE: "read:attack_protection",
  TENANT_SETTINGS_SCOPE: "read:tenant_settings",
  EMAIL_PROVIDER_SCOPE: "read:email_provider",
  EMAIL_TEMPLATES_SCOPE: "read:email_templates",
  MFA_POLICIES_SCOPE: "read:mfa_policies",
  MFA_FACTORS_SCOPE: "read:guardian_factors",
  REQUIRED_SCOPES:
    "read:tenant_settings read:custom_domains read:prompts read:clients read:connections read:connections_options read:resource_servers read:client_grants read:roles read:branding read:email_provider read:email_templates read:phone_providers read:phone_templates read:shields read:attack_protection read:self_service_profiles read:guardian_factors read:mfa_policies read:actions read:log_streams read:logs read:network_acls read:event_streams",
  LOG_TYPES: [
    "s",
    "f",
    "fs",
    "ss",
    "fu",
    "fp",
    "scoa",
    "fcoa",
    "sepft",
    "fepft",
  ],
  EMAIL_TEMPLATES_NAMES: {
    verify_email: "Verification Email (Link)",
    verify_email_by_code: "Verification Email (Code)",
    welcome_email: "Welcome Email",
    enrollment_email: "Enroll in Multifactor Authentication",
    reset_email: "Change Password (Link)",
    reset_email_by_code: "Change Password (Code)",
    blocked_account: "Blocked Account Email",
    stolen_credentials: "Password Breach Alert",
    mfa_oob_code: "Verification Code for Email MFA",
    user_invitation: "User Invitation",
  },
  EMAIL_TEMPLATES_TYPES: [
    "verify_email",
    "verify_email_by_code",
    "welcome_email",
    "enrollment_email",
    "reset_email",
    "reset_email_by_code",
    "blocked_account",
    "stolen_credentials",
    "mfa_oob_code",
    "user_invitation",
  ]
};
